Repository miaowware/qrm-resources, pull requests merged in 2020-11, with the labels that each got.

#12 Added the script for getting the hashes
  LICENSE-BSD-3-CLAUSE
  README.md
  gethashes.py
  undohashed.py
Labels: enhancement, hacktoberfest-accepted

#15 Synced maps and charts with qrm2
  CHANGELOG.md
  resources/bandcharts.1.json
  resources/bandcharts/au.png
  resources/bandcharts/it_hf.png
  resources/bandcharts/it_shf.png
  resources/bandcharts/it_vhf.png
  resources/bandcharts/jp.png
  resources/maps.1.json
Labels: enhancement

#16 Removed the slashes from the filenames in resources
  index.json
Labels: bug

#22 add _config.yml with theme and excludes
  _config.yml
Labels: easy, tooling

#23 add philippines band chart
  CHANGELOG.md
  resources/bandcharts.1.json
  resources/bandcharts/ph.png
Labels: enhancement

#24 remove superfluous slashes
  resources/bandcharts.1.json
  resources/imgs.1.json
  resources/maps.1.json
Labels: bug
