Repository miaowware/qrm-resources, pull requests merged in 2020-10, with the labels that each got.

#1 add deploy and release workflows
  .github/workflows/deploy-site.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: easy, priority-med, tooling

#3 Added the resources + basic index structure
  .gitignore
  README.md
  docs/maps-charts-format.md
  index.json
  resources/bandcharts.1.json
  resources/bandcharts/ca.png
  resources/bandcharts/cn.png
  resources/bandcharts/mx.png
  resources/bandcharts/nl.png
  resources/bandcharts/us.png
  resources/imgs.1.json
  resources/imgs/worksplit.jpg
  resources/maps.1.json
  resources/maps/arrl-rac.png
  resources/maps/ca.png
  resources/maps/cn.png
  resources/maps/cq-zones.png
  resources/maps/itu-regions.png
  resources/maps/itu-zones.png
  resources/maps/us.png
  resources/morse.1.json
  resources/phonetics.1.json
  resources/qcodes.1.json
  resources/words.1.txt
Labels: enhancement

#2 add jekyll exclude
  _config.yml
Labels: easy, priority-low, tooling

#10 Bump changelog 2020.10.1 + Add hashes
  CHANGELOG.md
  index.json
Labels: enhancement
