Repository miaowware/qrm-resources, pull requests merged in 2024-07, with the labels that each got.

#69 release prep 2024.7.1
  CHANGELOG.md
  gethashes.py
  resources/index.json
Labels: documentation

#70 resources/bandcharts/bg: shrink significantly
  CHANGELOG.md
  resources/bandcharts/bg.png
Labels: bug

#71 scripts: various cleanups
  .flake8
  gethashes.py
  undohashed.py
Labels: code cleanup, Skip-Changelog
